
get:
  summary: List all Leds
  operationId: getLeds
  responses:
    '200':
      description: A list of Leds
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components.yaml#/schemas/Led'
post:
  summary: Update Led list
  operationId: setLeds
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '../components.yaml#/schemas/Led'
  responses:
    '204':
      description: Updated leds
    '400':
      description: Bad requests