get:
  summary: List all servos
  operationId: getServos
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components.yaml#/schemas/Servo'

post:
  summary: Update a servos
  operationId: setServos
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '../components.yaml#/schemas/Servo'
  responses:
    '204':
      description: Updated servos
    '400':
      description: Bad requests



