get:
  summary: Get the list of WiFi credentials
  operationId: getWifiCredentials
  responses:
    '200':
      description: A list of WiFi credentials
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components.yaml#/schemas/WifiCredential'

post:
  summary: Update List of WiFi credentials
  operationId: setWifiCredentials
  requestBody:
    description: List of WiFi credentials to be stored
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '../components.yaml#/schemas/WifiCredential'
  responses:
    '204':
      description: WiFi credential added successfully
