
openapi: 3.0.0
info:
  title: WiFi Credentials API
  description: An API to manage WiFi credentials
  version: 1.0.0
servers:
  - url: '//'
  - url: 'http://192.168.0.93/'
  - url: 'http://192.168.4.1/'
  - url: 'http://192.168.178.181/'

  

paths:
  /api/config/wifi/credentials:
    $ref: 'paths/config-wifi-credentials.yaml'
  /api/config/leds:
    $ref: 'paths/config-leds.yaml'
  /api/config/servos:
    $ref: 'paths/config-servos.yaml'  
  /api/led:
    $ref: 'paths/led.yaml'
  /api/status:
    $ref: 'paths/status.yaml'
  /api/remote/speed:
    $ref: 'paths/remote-speed.yaml'  
  /api/remote/position:
    $ref: 'paths/remote-position.yaml'  
  /api/remote/mode:
    $ref: 'paths/remote-mode.yaml'
  /api/motion/:
    $ref: 'paths/motion.yaml'  
  # /api/motion/{motionId}:
  #   $ref: 'paths/motion-[id].yaml'  
  # # /api/motion/{motionId}/posture':
  # #   $ref: 'paths/motion-[id]-posture.yaml'
  # # /api/motion/{motionId}/posture/{postureId}':
  # #   $ref: 'paths/motion-[id]-posture-[id].yaml'  